<?php
include('./config.php');
$newpaste = $_POST['paste'];
$conn = mysql_connect ($settings['mysql_server'], $settings['mysql_user'], $settings['mysql_password']) or die ('<h1>500 Internal Server error.</h1><hr><i>Generated by /bin/paste on '. $_SERVER['HTTP_HOST'] .'.');
mysql_select_db($settings['mysql_database']);
$newpaste = mysql_real_escape_string($newpaste); //Escaped. Phew.
$hash = sha1($newpaste);
$new = true;
$abfrage = 'SELECT * FROM '.$settings['mysql_table_paste'].' WHERE sha1 = \''.$hash.'\'';
$ergebnis = mysql_query($abfrage);
echo mysql_error();
while($row = mysql_fetch_object($ergebnis)) {
   $new = false;
}

if($new == true) {
	echo mysql_error(); //Just in case, return '' if everything went well.
	$query = 'INSERT INTO '.$settings['mysql_table_paste'].' (sha1, paste) VALUES (\''.$hash.'\', \''.$newpaste.'\')';
	mysql_query($query);
}

echo '<form>
	  <b>Shell Script:</p><input style="width: 50%;" type="text" value="curl -s http://bin.truesebi.biz/plain.php?id='.$hash.' | /bin/sh"><br>
	  <b>Formatted Link (Syntax highlighted):</p><input style="width: 50%;" type="text" value="Coming soon!"><br>
	 ';
?>
