<?php
error_reporting(E_ALL);
$newpaste = $_POST['paste'];
$conn = mysql_connect ("localhost", "user", "pass") or die ('<h1>500 Internal Server error.</h1><hr><i>Generated by /bin/paste.');
mysql_select_db("truesebi_paste");
$newpaste = mysql_real_escape_string($newpaste); //Escaped. Phew.
$hash = sha1($newpaste);
$new = true;
$abfrage = "SELECT * FROM pastes WHERE sha1 = '$hash'";
$ergebnis = mysql_query($abfrage);
echo mysql_error();
while($row = mysql_fetch_object($ergebnis))
   {
   $new = false;
   }
if($new == true){
	echo mysql_error();

$eintrag = "INSERT INTO pastes (sha1, paste) VALUES ('$hash', '$newpaste')";
$eintragen = mysql_query($eintrag);
}

echo '<form>
	  <b>Shell Script:</p><input style="width: 50%;" type="text" value="curl -s http://bin.truesebi.biz/plain.php?id='.$hash.' | /bin/sh"><br>
	  <b>Formatted Link (Syntax highlighted):</p><input style="width: 50%;" type="text" value="Coming soon!"><br>
	 ';
?>
